.PHONY: init run run-mac

init:
	python3 -m venv venv

run:
	venv/bin/pip install pytest
	venv/bin/pytest -v test_calculator.py

run-mac:
	venv/bin/pip install pytest
	venv/bin/pytest -v test_calculator.py
