init:
	python3 -m venv venv && . venv/bin/activate && python3 -m pip install -r requirements.txt && python3 -m pytest -v test_jsonplaceholder.py

init-mac:
	python3 -m venv venv && . venv/bin/activate && python3 -m pip install -r requirements.txt && python3 -m pytest -v test_jsonplaceholder.py
